### ISSUE TITLE
project table required

### ISSUE THREAD

**Issue by AstraLuma** [duckinator/bork#349] opened 2023-11-30 04:33 UTC
bork zipapps require that a `project` table appears in `pyproject.toml`. Poetry-based projects use `tool.poetry` instead.

**Comment by duckinator** [comment] 2023-12-01 00:40
https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata

> The lack of a [project] table implicitly means the [build backend](https://packaging.python.org/en/latest/glossary/#term-Build-Backend) will dynamically provide all keys.

It sounds like this is a subset of #339. I'm leaving this open because it's a concrete, distinct example that would be useful to add tests for.

**Comment by duckinator** [comment] 2023-12-01 00:43
Okay, it helps if I _read_ #339 in its entirety, maybe. This is a duplicate of that, but with a few more details. I'm going to add some info to #339 then close this issue.

**Comment by duckinator** [comment] 2023-12-01 00:46
Closing as a duplicate of #339.

**Closed by duckinator** 2023-12-01 00:46 UTC
